/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public enum BooleanType {
  BT_FALSE,
  BT_TRUE;

  public final int swigValue() {
    return swigValue;
  }

  public static BooleanType swigToEnum(int swigValue) {
    BooleanType[] swigValues = BooleanType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (BooleanType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + BooleanType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private BooleanType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private BooleanType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private BooleanType(BooleanType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

