/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class Bounds extends SubjectTo {
  private long swigCPtr;

  protected Bounds(long cPtr, boolean cMemoryOwn) {
    super(qpOASESJNI.Bounds_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Bounds obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qpOASESJNI.delete_Bounds(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Bounds() {
    this(qpOASESJNI.new_Bounds__SWIG_0(), true);
  }

  public Bounds(int _n) {
    this(qpOASESJNI.new_Bounds__SWIG_1(_n), true);
  }

  public Bounds(Bounds rhs) {
    this(qpOASESJNI.new_Bounds__SWIG_2(Bounds.getCPtr(rhs), rhs), true);
  }

  public returnValue init(int _n) {
    return returnValue.swigToEnum(qpOASESJNI.Bounds_init__SWIG_0(swigCPtr, this, _n));
  }

  public returnValue init() {
    return returnValue.swigToEnum(qpOASESJNI.Bounds_init__SWIG_1(swigCPtr, this));
  }

  public returnValue setupBound(int number, SubjectToStatus _status) {
    return returnValue.swigToEnum(qpOASESJNI.Bounds_setupBound(swigCPtr, this, number, _status.swigValue()));
  }

  public returnValue setupAllFree() {
    return returnValue.swigToEnum(qpOASESJNI.Bounds_setupAllFree(swigCPtr, this));
  }

  public returnValue setupAllLower() {
    return returnValue.swigToEnum(qpOASESJNI.Bounds_setupAllLower(swigCPtr, this));
  }

  public returnValue setupAllUpper() {
    return returnValue.swigToEnum(qpOASESJNI.Bounds_setupAllUpper(swigCPtr, this));
  }

  public returnValue moveFixedToFree(int number) {
    return returnValue.swigToEnum(qpOASESJNI.Bounds_moveFixedToFree(swigCPtr, this, number));
  }

  public returnValue moveFreeToFixed(int number, SubjectToStatus _status) {
    return returnValue.swigToEnum(qpOASESJNI.Bounds_moveFreeToFixed(swigCPtr, this, number, _status.swigValue()));
  }

  public returnValue flipFixed(int number) {
    return returnValue.swigToEnum(qpOASESJNI.Bounds_flipFixed(swigCPtr, this, number));
  }

  public returnValue swapFree(int number1, int number2) {
    return returnValue.swigToEnum(qpOASESJNI.Bounds_swapFree(swigCPtr, this, number1, number2));
  }

  public int getNV() {
    return qpOASESJNI.Bounds_getNV(swigCPtr, this);
  }

  public int getNFV() {
    return qpOASESJNI.Bounds_getNFV(swigCPtr, this);
  }

  public int getNBV() {
    return qpOASESJNI.Bounds_getNBV(swigCPtr, this);
  }

  public int getNUV() {
    return qpOASESJNI.Bounds_getNUV(swigCPtr, this);
  }

  public int getNFR() {
    return qpOASESJNI.Bounds_getNFR(swigCPtr, this);
  }

  public int getNFX() {
    return qpOASESJNI.Bounds_getNFX(swigCPtr, this);
  }

  public Indexlist getFree() {
    long cPtr = qpOASESJNI.Bounds_getFree(swigCPtr, this);
    return (cPtr == 0) ? null : new Indexlist(cPtr, false);
  }

  public Indexlist getFixed() {
    long cPtr = qpOASESJNI.Bounds_getFixed(swigCPtr, this);
    return (cPtr == 0) ? null : new Indexlist(cPtr, false);
  }

  public returnValue shift(int offset) {
    return returnValue.swigToEnum(qpOASESJNI.Bounds_shift(swigCPtr, this, offset));
  }

  public returnValue rotate(int offset) {
    return returnValue.swigToEnum(qpOASESJNI.Bounds_rotate(swigCPtr, this, offset));
  }

  public returnValue print() {
    return returnValue.swigToEnum(qpOASESJNI.Bounds_print(swigCPtr, this));
  }

}
