/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class Constraints extends SubjectTo {
  private long swigCPtr;

  protected Constraints(long cPtr, boolean cMemoryOwn) {
    super(qpOASESJNI.Constraints_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Constraints obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qpOASESJNI.delete_Constraints(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Constraints() {
    this(qpOASESJNI.new_Constraints__SWIG_0(), true);
  }

  public Constraints(int _n) {
    this(qpOASESJNI.new_Constraints__SWIG_1(_n), true);
  }

  public Constraints(Constraints rhs) {
    this(qpOASESJNI.new_Constraints__SWIG_2(Constraints.getCPtr(rhs), rhs), true);
  }

  public returnValue init(int _n) {
    return returnValue.swigToEnum(qpOASESJNI.Constraints_init__SWIG_0(swigCPtr, this, _n));
  }

  public returnValue init() {
    return returnValue.swigToEnum(qpOASESJNI.Constraints_init__SWIG_1(swigCPtr, this));
  }

  public returnValue setupConstraint(int number, SubjectToStatus _status) {
    return returnValue.swigToEnum(qpOASESJNI.Constraints_setupConstraint(swigCPtr, this, number, _status.swigValue()));
  }

  public returnValue setupAllInactive() {
    return returnValue.swigToEnum(qpOASESJNI.Constraints_setupAllInactive(swigCPtr, this));
  }

  public returnValue setupAllLower() {
    return returnValue.swigToEnum(qpOASESJNI.Constraints_setupAllLower(swigCPtr, this));
  }

  public returnValue setupAllUpper() {
    return returnValue.swigToEnum(qpOASESJNI.Constraints_setupAllUpper(swigCPtr, this));
  }

  public returnValue moveActiveToInactive(int number) {
    return returnValue.swigToEnum(qpOASESJNI.Constraints_moveActiveToInactive(swigCPtr, this, number));
  }

  public returnValue moveInactiveToActive(int number, SubjectToStatus _status) {
    return returnValue.swigToEnum(qpOASESJNI.Constraints_moveInactiveToActive(swigCPtr, this, number, _status.swigValue()));
  }

  public returnValue flipFixed(int number) {
    return returnValue.swigToEnum(qpOASESJNI.Constraints_flipFixed(swigCPtr, this, number));
  }

  public int getNC() {
    return qpOASESJNI.Constraints_getNC(swigCPtr, this);
  }

  public int getNEC() {
    return qpOASESJNI.Constraints_getNEC(swigCPtr, this);
  }

  public int getNIC() {
    return qpOASESJNI.Constraints_getNIC(swigCPtr, this);
  }

  public int getNUC() {
    return qpOASESJNI.Constraints_getNUC(swigCPtr, this);
  }

  public int getNAC() {
    return qpOASESJNI.Constraints_getNAC(swigCPtr, this);
  }

  public int getNIAC() {
    return qpOASESJNI.Constraints_getNIAC(swigCPtr, this);
  }

  public Indexlist getActive() {
    long cPtr = qpOASESJNI.Constraints_getActive(swigCPtr, this);
    return (cPtr == 0) ? null : new Indexlist(cPtr, false);
  }

  public Indexlist getInactive() {
    long cPtr = qpOASESJNI.Constraints_getInactive(swigCPtr, this);
    return (cPtr == 0) ? null : new Indexlist(cPtr, false);
  }

  public returnValue shift(int offset) {
    return returnValue.swigToEnum(qpOASESJNI.Constraints_shift(swigCPtr, this, offset));
  }

  public returnValue rotate(int offset) {
    return returnValue.swigToEnum(qpOASESJNI.Constraints_rotate(swigCPtr, this, offset));
  }

  public returnValue print() {
    return returnValue.swigToEnum(qpOASESJNI.Constraints_print(swigCPtr, this));
  }

}
