/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class DenseMatrix extends Matrix {
  private long swigCPtr;

  protected DenseMatrix(long cPtr, boolean cMemoryOwn) {
    super(qpOASESJNI.DenseMatrix_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DenseMatrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qpOASESJNI.delete_DenseMatrix(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DenseMatrix() {
    this(qpOASESJNI.new_DenseMatrix__SWIG_0(), true);
  }

  public DenseMatrix(int m, int n, int lD, double[] v) {
    this(qpOASESJNI.new_DenseMatrix__SWIG_1(m, n, lD, v), true);
  }

  public void free() {
    qpOASESJNI.DenseMatrix_free(swigCPtr, this);
  }

  public Matrix duplicate() {
    long cPtr = qpOASESJNI.DenseMatrix_duplicate(swigCPtr, this);
    return (cPtr == 0) ? null : new Matrix(cPtr, false);
  }

  public double diag(int i) {
    return qpOASESJNI.DenseMatrix_diag(swigCPtr, this, i);
  }

  public BooleanType isDiag() {
    return BooleanType.swigToEnum(qpOASESJNI.DenseMatrix_isDiag(swigCPtr, this));
  }

  public double getNorm(int type) {
    return qpOASESJNI.DenseMatrix_getNorm__SWIG_0(swigCPtr, this, type);
  }

  public double getNorm() {
    return qpOASESJNI.DenseMatrix_getNorm__SWIG_1(swigCPtr, this);
  }

  public double getRowNorm(int rNum, int type) {
    return qpOASESJNI.DenseMatrix_getRowNorm__SWIG_0(swigCPtr, this, rNum, type);
  }

  public double getRowNorm(int rNum) {
    return qpOASESJNI.DenseMatrix_getRowNorm__SWIG_1(swigCPtr, this, rNum);
  }

  public returnValue getRow(int rNum, Indexlist icols, double alpha, double[] row) {
    return returnValue.swigToEnum(qpOASESJNI.DenseMatrix_getRow(swigCPtr, this, rNum, Indexlist.getCPtr(icols), icols, alpha, row));
  }

  public returnValue getCol(int cNum, Indexlist irows, double alpha, double[] col) {
    return returnValue.swigToEnum(qpOASESJNI.DenseMatrix_getCol(swigCPtr, this, cNum, Indexlist.getCPtr(irows), irows, alpha, col));
  }

  public returnValue times(int xN, double alpha, double[] x, int xLD, double beta, double[] y, int yLD) {
    return returnValue.swigToEnum(qpOASESJNI.DenseMatrix_times__SWIG_0(swigCPtr, this, xN, alpha, x, xLD, beta, y, yLD));
  }

  public returnValue transTimes(int xN, double alpha, double[] x, int xLD, double beta, double[] y, int yLD) {
    return returnValue.swigToEnum(qpOASESJNI.DenseMatrix_transTimes__SWIG_0(swigCPtr, this, xN, alpha, x, xLD, beta, y, yLD));
  }

  public returnValue times(Indexlist irows, Indexlist icols, int xN, double alpha, double[] x, int xLD, double beta, double[] y, int yLD, BooleanType yCompr) {
    return returnValue.swigToEnum(qpOASESJNI.DenseMatrix_times__SWIG_1(swigCPtr, this, Indexlist.getCPtr(irows), irows, Indexlist.getCPtr(icols), icols, xN, alpha, x, xLD, beta, y, yLD, yCompr.swigValue()));
  }

  public returnValue times(Indexlist irows, Indexlist icols, int xN, double alpha, double[] x, int xLD, double beta, double[] y, int yLD) {
    return returnValue.swigToEnum(qpOASESJNI.DenseMatrix_times__SWIG_2(swigCPtr, this, Indexlist.getCPtr(irows), irows, Indexlist.getCPtr(icols), icols, xN, alpha, x, xLD, beta, y, yLD));
  }

  public returnValue transTimes(Indexlist irows, Indexlist icols, int xN, double alpha, double[] x, int xLD, double beta, double[] y, int yLD) {
    return returnValue.swigToEnum(qpOASESJNI.DenseMatrix_transTimes__SWIG_1(swigCPtr, this, Indexlist.getCPtr(irows), irows, Indexlist.getCPtr(icols), icols, xN, alpha, x, xLD, beta, y, yLD));
  }

  public returnValue addToDiag(double alpha) {
    return returnValue.swigToEnum(qpOASESJNI.DenseMatrix_addToDiag(swigCPtr, this, alpha));
  }

  public returnValue print(String name) {
    return returnValue.swigToEnum(qpOASESJNI.DenseMatrix_print__SWIG_0(swigCPtr, this, name));
  }

  public returnValue print() {
    return returnValue.swigToEnum(qpOASESJNI.DenseMatrix_print__SWIG_1(swigCPtr, this));
  }

}
