/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class MatMatrixHeader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MatMatrixHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MatMatrixHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qpOASESJNI.delete_MatMatrixHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNumericFormat(int value) {
    qpOASESJNI.MatMatrixHeader_numericFormat_set(swigCPtr, this, value);
  }

  public int getNumericFormat() {
    return qpOASESJNI.MatMatrixHeader_numericFormat_get(swigCPtr, this);
  }

  public void setNRows(int value) {
    qpOASESJNI.MatMatrixHeader_nRows_set(swigCPtr, this, value);
  }

  public int getNRows() {
    return qpOASESJNI.MatMatrixHeader_nRows_get(swigCPtr, this);
  }

  public void setNCols(int value) {
    qpOASESJNI.MatMatrixHeader_nCols_set(swigCPtr, this, value);
  }

  public int getNCols() {
    return qpOASESJNI.MatMatrixHeader_nCols_get(swigCPtr, this);
  }

  public void setImaginaryPart(int value) {
    qpOASESJNI.MatMatrixHeader_imaginaryPart_set(swigCPtr, this, value);
  }

  public int getImaginaryPart() {
    return qpOASESJNI.MatMatrixHeader_imaginaryPart_get(swigCPtr, this);
  }

  public void setNCharName(int value) {
    qpOASESJNI.MatMatrixHeader_nCharName_set(swigCPtr, this, value);
  }

  public int getNCharName() {
    return qpOASESJNI.MatMatrixHeader_nCharName_get(swigCPtr, this);
  }

  public MatMatrixHeader() {
    this(qpOASESJNI.new_MatMatrixHeader(), true);
  }

}
