/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class Matrix {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Matrix(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Matrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qpOASESJNI.delete_Matrix(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void free() {
    qpOASESJNI.Matrix_free(swigCPtr, this);
  }

  public Matrix duplicate() {
    long cPtr = qpOASESJNI.Matrix_duplicate(swigCPtr, this);
    return (cPtr == 0) ? null : new Matrix(cPtr, false);
  }

  public double diag(int i) {
    return qpOASESJNI.Matrix_diag(swigCPtr, this, i);
  }

  public BooleanType isDiag() {
    return BooleanType.swigToEnum(qpOASESJNI.Matrix_isDiag(swigCPtr, this));
  }

  public double getNorm(int type) {
    return qpOASESJNI.Matrix_getNorm__SWIG_0(swigCPtr, this, type);
  }

  public double getNorm() {
    return qpOASESJNI.Matrix_getNorm__SWIG_1(swigCPtr, this);
  }

  public double getRowNorm(int rNum, int type) {
    return qpOASESJNI.Matrix_getRowNorm__SWIG_0(swigCPtr, this, rNum, type);
  }

  public double getRowNorm(int rNum) {
    return qpOASESJNI.Matrix_getRowNorm__SWIG_1(swigCPtr, this, rNum);
  }

  public returnValue getRow(int rNum, Indexlist icols, double alpha, double[] row) {
    return returnValue.swigToEnum(qpOASESJNI.Matrix_getRow(swigCPtr, this, rNum, Indexlist.getCPtr(icols), icols, alpha, row));
  }

  public returnValue getCol(int cNum, Indexlist irows, double alpha, double[] col) {
    return returnValue.swigToEnum(qpOASESJNI.Matrix_getCol(swigCPtr, this, cNum, Indexlist.getCPtr(irows), irows, alpha, col));
  }

  public returnValue times(int xN, double alpha, double[] x, int xLD, double beta, double[] y, int yLD) {
    return returnValue.swigToEnum(qpOASESJNI.Matrix_times__SWIG_0(swigCPtr, this, xN, alpha, x, xLD, beta, y, yLD));
  }

  public returnValue transTimes(int xN, double alpha, double[] x, int xLD, double beta, double[] y, int yLD) {
    return returnValue.swigToEnum(qpOASESJNI.Matrix_transTimes__SWIG_0(swigCPtr, this, xN, alpha, x, xLD, beta, y, yLD));
  }

  public returnValue times(Indexlist irows, Indexlist icols, int xN, double alpha, double[] x, int xLD, double beta, double[] y, int yLD, BooleanType yCompr) {
    return returnValue.swigToEnum(qpOASESJNI.Matrix_times__SWIG_1(swigCPtr, this, Indexlist.getCPtr(irows), irows, Indexlist.getCPtr(icols), icols, xN, alpha, x, xLD, beta, y, yLD, yCompr.swigValue()));
  }

  public returnValue times(Indexlist irows, Indexlist icols, int xN, double alpha, double[] x, int xLD, double beta, double[] y, int yLD) {
    return returnValue.swigToEnum(qpOASESJNI.Matrix_times__SWIG_2(swigCPtr, this, Indexlist.getCPtr(irows), irows, Indexlist.getCPtr(icols), icols, xN, alpha, x, xLD, beta, y, yLD));
  }

  public returnValue transTimes(Indexlist irows, Indexlist icols, int xN, double alpha, double[] x, int xLD, double beta, double[] y, int yLD) {
    return returnValue.swigToEnum(qpOASESJNI.Matrix_transTimes__SWIG_1(swigCPtr, this, Indexlist.getCPtr(irows), irows, Indexlist.getCPtr(icols), icols, xN, alpha, x, xLD, beta, y, yLD));
  }

  public returnValue addToDiag(double alpha) {
    return returnValue.swigToEnum(qpOASESJNI.Matrix_addToDiag(swigCPtr, this, alpha));
  }

  public returnValue print(String name) {
    return returnValue.swigToEnum(qpOASESJNI.Matrix_print__SWIG_0(swigCPtr, this, name));
  }

  public returnValue print() {
    return returnValue.swigToEnum(qpOASESJNI.Matrix_print__SWIG_1(swigCPtr, this));
  }

  public BooleanType needToFreeMemory() {
    return BooleanType.swigToEnum(qpOASESJNI.Matrix_needToFreeMemory(swigCPtr, this));
  }

  public void doFreeMemory() {
    qpOASESJNI.Matrix_doFreeMemory(swigCPtr, this);
  }

  public void doNotFreeMemory() {
    qpOASESJNI.Matrix_doNotFreeMemory(swigCPtr, this);
  }

}
