/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class MessageHandling {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MessageHandling(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MessageHandling obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qpOASESJNI.delete_MessageHandling(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MessageHandling() {
    this(qpOASESJNI.new_MessageHandling__SWIG_0(), true);
  }

  public MessageHandling(SWIGTYPE_p_FILE _outputFile) {
    this(qpOASESJNI.new_MessageHandling__SWIG_1(SWIGTYPE_p_FILE.getCPtr(_outputFile)), true);
  }

  public MessageHandling(VisibilityStatus _errorVisibility, VisibilityStatus _warningVisibility, VisibilityStatus _infoVisibility) {
    this(qpOASESJNI.new_MessageHandling__SWIG_2(_errorVisibility.swigValue(), _warningVisibility.swigValue(), _infoVisibility.swigValue()), true);
  }

  public MessageHandling(SWIGTYPE_p_FILE _outputFile, VisibilityStatus _errorVisibility, VisibilityStatus _warningVisibility, VisibilityStatus _infoVisibility) {
    this(qpOASESJNI.new_MessageHandling__SWIG_3(SWIGTYPE_p_FILE.getCPtr(_outputFile), _errorVisibility.swigValue(), _warningVisibility.swigValue(), _infoVisibility.swigValue()), true);
  }

  public MessageHandling(MessageHandling rhs) {
    this(qpOASESJNI.new_MessageHandling__SWIG_4(MessageHandling.getCPtr(rhs), rhs), true);
  }

  public returnValue throwError(returnValue Enumber, String additionaltext, String functionname, String filename, long linenumber, VisibilityStatus localVisibilityStatus) {
    return returnValue.swigToEnum(qpOASESJNI.MessageHandling_throwError(swigCPtr, this, Enumber.swigValue(), additionaltext, functionname, filename, linenumber, localVisibilityStatus.swigValue()));
  }

  public returnValue throwWarning(returnValue Wnumber, String additionaltext, String functionname, String filename, long linenumber, VisibilityStatus localVisibilityStatus) {
    return returnValue.swigToEnum(qpOASESJNI.MessageHandling_throwWarning(swigCPtr, this, Wnumber.swigValue(), additionaltext, functionname, filename, linenumber, localVisibilityStatus.swigValue()));
  }

  public returnValue throwInfo(returnValue Inumber, String additionaltext, String functionname, String filename, long linenumber, VisibilityStatus localVisibilityStatus) {
    return returnValue.swigToEnum(qpOASESJNI.MessageHandling_throwInfo(swigCPtr, this, Inumber.swigValue(), additionaltext, functionname, filename, linenumber, localVisibilityStatus.swigValue()));
  }

  public returnValue reset() {
    return returnValue.swigToEnum(qpOASESJNI.MessageHandling_reset(swigCPtr, this));
  }

  public returnValue listAllMessages() {
    return returnValue.swigToEnum(qpOASESJNI.MessageHandling_listAllMessages(swigCPtr, this));
  }

  public VisibilityStatus getErrorVisibilityStatus() {
    return VisibilityStatus.swigToEnum(qpOASESJNI.MessageHandling_getErrorVisibilityStatus(swigCPtr, this));
  }

  public VisibilityStatus getWarningVisibilityStatus() {
    return VisibilityStatus.swigToEnum(qpOASESJNI.MessageHandling_getWarningVisibilityStatus(swigCPtr, this));
  }

  public VisibilityStatus getInfoVisibilityStatus() {
    return VisibilityStatus.swigToEnum(qpOASESJNI.MessageHandling_getInfoVisibilityStatus(swigCPtr, this));
  }

  public SWIGTYPE_p_FILE getOutputFile() {
    long cPtr = qpOASESJNI.MessageHandling_getOutputFile(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public int getErrorCount() {
    return qpOASESJNI.MessageHandling_getErrorCount(swigCPtr, this);
  }

  public void setErrorVisibilityStatus(VisibilityStatus _errorVisibility) {
    qpOASESJNI.MessageHandling_setErrorVisibilityStatus(swigCPtr, this, _errorVisibility.swigValue());
  }

  public void setWarningVisibilityStatus(VisibilityStatus _warningVisibility) {
    qpOASESJNI.MessageHandling_setWarningVisibilityStatus(swigCPtr, this, _warningVisibility.swigValue());
  }

  public void setInfoVisibilityStatus(VisibilityStatus _infoVisibility) {
    qpOASESJNI.MessageHandling_setInfoVisibilityStatus(swigCPtr, this, _infoVisibility.swigValue());
  }

  public void setOutputFile(SWIGTYPE_p_FILE _outputFile) {
    qpOASESJNI.MessageHandling_setOutputFile(swigCPtr, this, SWIGTYPE_p_FILE.getCPtr(_outputFile));
  }

  public returnValue setErrorCount(int _errorCount) {
    return returnValue.swigToEnum(qpOASESJNI.MessageHandling_setErrorCount(swigCPtr, this, _errorCount));
  }

  public static String getErrorCodeMessage(returnValue _returnValue) {
    return qpOASESJNI.MessageHandling_getErrorCodeMessage(_returnValue.swigValue());
  }

}
