/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class Options {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qpOASESJNI.delete_Options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Options() {
    this(qpOASESJNI.new_Options__SWIG_0(), true);
  }

  public Options(Options rhs) {
    this(qpOASESJNI.new_Options__SWIG_1(Options.getCPtr(rhs), rhs), true);
  }

  public returnValue setToDefault() {
    return returnValue.swigToEnum(qpOASESJNI.Options_setToDefault(swigCPtr, this));
  }

  public returnValue setToReliable() {
    return returnValue.swigToEnum(qpOASESJNI.Options_setToReliable(swigCPtr, this));
  }

  public returnValue setToMPC() {
    return returnValue.swigToEnum(qpOASESJNI.Options_setToMPC(swigCPtr, this));
  }

  public returnValue setToFast() {
    return returnValue.swigToEnum(qpOASESJNI.Options_setToFast(swigCPtr, this));
  }

  public returnValue ensureConsistency() {
    return returnValue.swigToEnum(qpOASESJNI.Options_ensureConsistency(swigCPtr, this));
  }

  public returnValue print() {
    return returnValue.swigToEnum(qpOASESJNI.Options_print(swigCPtr, this));
  }

  public void setPrintLevel(PrintLevel value) {
    qpOASESJNI.Options_printLevel_set(swigCPtr, this, value.swigValue());
  }

  public PrintLevel getPrintLevel() {
    return PrintLevel.swigToEnum(qpOASESJNI.Options_printLevel_get(swigCPtr, this));
  }

  public void setEnableRamping(BooleanType value) {
    qpOASESJNI.Options_enableRamping_set(swigCPtr, this, value.swigValue());
  }

  public BooleanType getEnableRamping() {
    return BooleanType.swigToEnum(qpOASESJNI.Options_enableRamping_get(swigCPtr, this));
  }

  public void setEnableFarBounds(BooleanType value) {
    qpOASESJNI.Options_enableFarBounds_set(swigCPtr, this, value.swigValue());
  }

  public BooleanType getEnableFarBounds() {
    return BooleanType.swigToEnum(qpOASESJNI.Options_enableFarBounds_get(swigCPtr, this));
  }

  public void setEnableFlippingBounds(BooleanType value) {
    qpOASESJNI.Options_enableFlippingBounds_set(swigCPtr, this, value.swigValue());
  }

  public BooleanType getEnableFlippingBounds() {
    return BooleanType.swigToEnum(qpOASESJNI.Options_enableFlippingBounds_get(swigCPtr, this));
  }

  public void setEnableRegularisation(BooleanType value) {
    qpOASESJNI.Options_enableRegularisation_set(swigCPtr, this, value.swigValue());
  }

  public BooleanType getEnableRegularisation() {
    return BooleanType.swigToEnum(qpOASESJNI.Options_enableRegularisation_get(swigCPtr, this));
  }

  public void setEnableFullLITests(BooleanType value) {
    qpOASESJNI.Options_enableFullLITests_set(swigCPtr, this, value.swigValue());
  }

  public BooleanType getEnableFullLITests() {
    return BooleanType.swigToEnum(qpOASESJNI.Options_enableFullLITests_get(swigCPtr, this));
  }

  public void setEnableNZCTests(BooleanType value) {
    qpOASESJNI.Options_enableNZCTests_set(swigCPtr, this, value.swigValue());
  }

  public BooleanType getEnableNZCTests() {
    return BooleanType.swigToEnum(qpOASESJNI.Options_enableNZCTests_get(swigCPtr, this));
  }

  public void setEnableDriftCorrection(int value) {
    qpOASESJNI.Options_enableDriftCorrection_set(swigCPtr, this, value);
  }

  public int getEnableDriftCorrection() {
    return qpOASESJNI.Options_enableDriftCorrection_get(swigCPtr, this);
  }

  public void setEnableCholeskyRefactorisation(int value) {
    qpOASESJNI.Options_enableCholeskyRefactorisation_set(swigCPtr, this, value);
  }

  public int getEnableCholeskyRefactorisation() {
    return qpOASESJNI.Options_enableCholeskyRefactorisation_get(swigCPtr, this);
  }

  public void setEnableEqualities(BooleanType value) {
    qpOASESJNI.Options_enableEqualities_set(swigCPtr, this, value.swigValue());
  }

  public BooleanType getEnableEqualities() {
    return BooleanType.swigToEnum(qpOASESJNI.Options_enableEqualities_get(swigCPtr, this));
  }

  public void setTerminationTolerance(double value) {
    qpOASESJNI.Options_terminationTolerance_set(swigCPtr, this, value);
  }

  public double getTerminationTolerance() {
    return qpOASESJNI.Options_terminationTolerance_get(swigCPtr, this);
  }

  public void setBoundTolerance(double value) {
    qpOASESJNI.Options_boundTolerance_set(swigCPtr, this, value);
  }

  public double getBoundTolerance() {
    return qpOASESJNI.Options_boundTolerance_get(swigCPtr, this);
  }

  public void setBoundRelaxation(double value) {
    qpOASESJNI.Options_boundRelaxation_set(swigCPtr, this, value);
  }

  public double getBoundRelaxation() {
    return qpOASESJNI.Options_boundRelaxation_get(swigCPtr, this);
  }

  public void setEpsNum(double value) {
    qpOASESJNI.Options_epsNum_set(swigCPtr, this, value);
  }

  public double getEpsNum() {
    return qpOASESJNI.Options_epsNum_get(swigCPtr, this);
  }

  public void setEpsDen(double value) {
    qpOASESJNI.Options_epsDen_set(swigCPtr, this, value);
  }

  public double getEpsDen() {
    return qpOASESJNI.Options_epsDen_get(swigCPtr, this);
  }

  public void setMaxPrimalJump(double value) {
    qpOASESJNI.Options_maxPrimalJump_set(swigCPtr, this, value);
  }

  public double getMaxPrimalJump() {
    return qpOASESJNI.Options_maxPrimalJump_get(swigCPtr, this);
  }

  public void setMaxDualJump(double value) {
    qpOASESJNI.Options_maxDualJump_set(swigCPtr, this, value);
  }

  public double getMaxDualJump() {
    return qpOASESJNI.Options_maxDualJump_get(swigCPtr, this);
  }

  public void setInitialRamping(double value) {
    qpOASESJNI.Options_initialRamping_set(swigCPtr, this, value);
  }

  public double getInitialRamping() {
    return qpOASESJNI.Options_initialRamping_get(swigCPtr, this);
  }

  public void setFinalRamping(double value) {
    qpOASESJNI.Options_finalRamping_set(swigCPtr, this, value);
  }

  public double getFinalRamping() {
    return qpOASESJNI.Options_finalRamping_get(swigCPtr, this);
  }

  public void setInitialFarBounds(double value) {
    qpOASESJNI.Options_initialFarBounds_set(swigCPtr, this, value);
  }

  public double getInitialFarBounds() {
    return qpOASESJNI.Options_initialFarBounds_get(swigCPtr, this);
  }

  public void setGrowFarBounds(double value) {
    qpOASESJNI.Options_growFarBounds_set(swigCPtr, this, value);
  }

  public double getGrowFarBounds() {
    return qpOASESJNI.Options_growFarBounds_get(swigCPtr, this);
  }

  public void setInitialStatusBounds(SubjectToStatus value) {
    qpOASESJNI.Options_initialStatusBounds_set(swigCPtr, this, value.swigValue());
  }

  public SubjectToStatus getInitialStatusBounds() {
    return SubjectToStatus.swigToEnum(qpOASESJNI.Options_initialStatusBounds_get(swigCPtr, this));
  }

  public void setEpsFlipping(double value) {
    qpOASESJNI.Options_epsFlipping_set(swigCPtr, this, value);
  }

  public double getEpsFlipping() {
    return qpOASESJNI.Options_epsFlipping_get(swigCPtr, this);
  }

  public void setNumRegularisationSteps(int value) {
    qpOASESJNI.Options_numRegularisationSteps_set(swigCPtr, this, value);
  }

  public int getNumRegularisationSteps() {
    return qpOASESJNI.Options_numRegularisationSteps_get(swigCPtr, this);
  }

  public void setEpsRegularisation(double value) {
    qpOASESJNI.Options_epsRegularisation_set(swigCPtr, this, value);
  }

  public double getEpsRegularisation() {
    return qpOASESJNI.Options_epsRegularisation_get(swigCPtr, this);
  }

  public void setNumRefinementSteps(int value) {
    qpOASESJNI.Options_numRefinementSteps_set(swigCPtr, this, value);
  }

  public int getNumRefinementSteps() {
    return qpOASESJNI.Options_numRefinementSteps_get(swigCPtr, this);
  }

  public void setEpsIterRef(double value) {
    qpOASESJNI.Options_epsIterRef_set(swigCPtr, this, value);
  }

  public double getEpsIterRef() {
    return qpOASESJNI.Options_epsIterRef_get(swigCPtr, this);
  }

  public void setEpsLITests(double value) {
    qpOASESJNI.Options_epsLITests_set(swigCPtr, this, value);
  }

  public double getEpsLITests() {
    return qpOASESJNI.Options_epsLITests_get(swigCPtr, this);
  }

  public void setEpsNZCTests(double value) {
    qpOASESJNI.Options_epsNZCTests_set(swigCPtr, this, value);
  }

  public double getEpsNZCTests() {
    return qpOASESJNI.Options_epsNZCTests_get(swigCPtr, this);
  }

  public void setEnableDropInfeasibles(BooleanType value) {
    qpOASESJNI.Options_enableDropInfeasibles_set(swigCPtr, this, value.swigValue());
  }

  public BooleanType getEnableDropInfeasibles() {
    return BooleanType.swigToEnum(qpOASESJNI.Options_enableDropInfeasibles_get(swigCPtr, this));
  }

  public void setDropBoundPriority(int value) {
    qpOASESJNI.Options_dropBoundPriority_set(swigCPtr, this, value);
  }

  public int getDropBoundPriority() {
    return qpOASESJNI.Options_dropBoundPriority_get(swigCPtr, this);
  }

  public void setDropEqConPriority(int value) {
    qpOASESJNI.Options_dropEqConPriority_set(swigCPtr, this, value);
  }

  public int getDropEqConPriority() {
    return qpOASESJNI.Options_dropEqConPriority_get(swigCPtr, this);
  }

  public void setDropIneqConPriority(int value) {
    qpOASESJNI.Options_dropIneqConPriority_set(swigCPtr, this, value);
  }

  public int getDropIneqConPriority() {
    return qpOASESJNI.Options_dropIneqConPriority_get(swigCPtr, this);
  }

}
