/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public enum PrintLevel {
  PL_DEBUG_ITER(qpOASESJNI.PL_DEBUG_ITER_get()),
  PL_TABULAR,
  PL_NONE,
  PL_LOW,
  PL_MEDIUM,
  PL_HIGH;

  public final int swigValue() {
    return swigValue;
  }

  public static PrintLevel swigToEnum(int swigValue) {
    PrintLevel[] swigValues = PrintLevel.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (PrintLevel swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + PrintLevel.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private PrintLevel() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private PrintLevel(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private PrintLevel(PrintLevel swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

