/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public interface qpOASESConstants {
  public final static int __FUNCTION__ = qpOASESJNI.__FUNCTION___get();
  public final static int __FILE__ = qpOASESJNI.__FILE___get();
  public final static int __LINE__ = qpOASESJNI.__LINE___get();
}
