/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class qpOASES implements qpOASESConstants {
  public static void setStdFile(SWIGTYPE_p_FILE value) {
    qpOASESJNI.stdFile_set(SWIGTYPE_p_FILE.getCPtr(value));
  }

  public static SWIGTYPE_p_FILE getStdFile() {
    long cPtr = qpOASESJNI.stdFile_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static MessageHandling getGlobalMessageHandler() {
    long cPtr = qpOASESJNI.getGlobalMessageHandler();
    return (cPtr == 0) ? null : new MessageHandling(cPtr, false);
  }

  public static returnValue initAndSolve(QProblem problem, double[] H_, double[] g_, double[] A_, double[] lb_, double[] ub_, double[] lbA_, double[] ubA_, int nWSR_, double[] xOpt) {
    return returnValue.swigToEnum(qpOASESJNI.initAndSolve__SWIG_0(QProblem.getCPtr(problem), problem, H_, g_, A_, lb_, ub_, lbA_, ubA_, nWSR_, xOpt));
  }

  public static returnValue initAndSolve(QProblem problem, double[] H_, double[] g_, double[] lb_, double[] ub_, int nWSR_, double[] xOpt) {
    return returnValue.swigToEnum(qpOASESJNI.initAndSolve__SWIG_1(QProblem.getCPtr(problem), problem, H_, g_, lb_, ub_, nWSR_, xOpt));
  }

}
