/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class QProblem extends QProblemB {
  private long swigCPtr;

  protected QProblem(long cPtr, boolean cMemoryOwn) {
    super(qpOASESJNI.QProblem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QProblem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qpOASESJNI.delete_QProblem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public QProblem() {
    this(qpOASESJNI.new_QProblem__SWIG_0(), true);
  }

  public QProblem(int _nV, int _nC, HessianType _hessianType) {
    this(qpOASESJNI.new_QProblem__SWIG_1(_nV, _nC, _hessianType.swigValue()), true);
  }

  public QProblem(int _nV, int _nC) {
    this(qpOASESJNI.new_QProblem__SWIG_2(_nV, _nC), true);
  }

  public QProblem(QProblem rhs) {
    this(qpOASESJNI.new_QProblem__SWIG_3(QProblem.getCPtr(rhs), rhs), true);
  }

  public returnValue reset() {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_reset(swigCPtr, this));
  }

  public returnValue init(SymmetricMatrix _H, double[] _g, Matrix _A, double[] _lb, double[] _ub, double[] _lbA, double[] _ubA, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_init__SWIG_0(swigCPtr, this, SymmetricMatrix.getCPtr(_H), _H, _g, Matrix.getCPtr(_A), _A, _lb, _ub, _lbA, _ubA, nWSR, cputime));
  }

  public returnValue init(SymmetricMatrix _H, double[] _g, Matrix _A, double[] _lb, double[] _ub, double[] _lbA, double[] _ubA, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_init__SWIG_1(swigCPtr, this, SymmetricMatrix.getCPtr(_H), _H, _g, Matrix.getCPtr(_A), _A, _lb, _ub, _lbA, _ubA, nWSR));
  }

  public returnValue init(double[] _H, double[] _g, double[] _A, double[] _lb, double[] _ub, double[] _lbA, double[] _ubA, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_init__SWIG_2(swigCPtr, this, _H, _g, _A, _lb, _ub, _lbA, _ubA, nWSR, cputime));
  }

  public returnValue init(double[] _H, double[] _g, double[] _A, double[] _lb, double[] _ub, double[] _lbA, double[] _ubA, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_init__SWIG_3(swigCPtr, this, _H, _g, _A, _lb, _ub, _lbA, _ubA, nWSR));
  }

  public returnValue init(String H_file, String g_file, String A_file, String lb_file, String ub_file, String lbA_file, String ubA_file, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_init__SWIG_4(swigCPtr, this, H_file, g_file, A_file, lb_file, ub_file, lbA_file, ubA_file, nWSR, cputime));
  }

  public returnValue init(String H_file, String g_file, String A_file, String lb_file, String ub_file, String lbA_file, String ubA_file, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_init__SWIG_5(swigCPtr, this, H_file, g_file, A_file, lb_file, ub_file, lbA_file, ubA_file, nWSR));
  }

  public returnValue init(SymmetricMatrix _H, double[] _g, Matrix _A, double[] _lb, double[] _ub, double[] _lbA, double[] _ubA, int[] nWSR, double[] cputime, double[] xOpt, double[] yOpt, Bounds guessedBounds, Constraints guessedConstraints) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_init__SWIG_6(swigCPtr, this, SymmetricMatrix.getCPtr(_H), _H, _g, Matrix.getCPtr(_A), _A, _lb, _ub, _lbA, _ubA, nWSR, cputime, xOpt, yOpt, Bounds.getCPtr(guessedBounds), guessedBounds, Constraints.getCPtr(guessedConstraints), guessedConstraints));
  }

  public returnValue init(double[] _H, double[] _g, double[] _A, double[] _lb, double[] _ub, double[] _lbA, double[] _ubA, int[] nWSR, double[] cputime, double[] xOpt, double[] yOpt, Bounds guessedBounds, Constraints guessedConstraints) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_init__SWIG_7(swigCPtr, this, _H, _g, _A, _lb, _ub, _lbA, _ubA, nWSR, cputime, xOpt, yOpt, Bounds.getCPtr(guessedBounds), guessedBounds, Constraints.getCPtr(guessedConstraints), guessedConstraints));
  }

  public returnValue init(String H_file, String g_file, String A_file, String lb_file, String ub_file, String lbA_file, String ubA_file, int[] nWSR, double[] cputime, double[] xOpt, double[] yOpt, Bounds guessedBounds, Constraints guessedConstraints) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_init__SWIG_8(swigCPtr, this, H_file, g_file, A_file, lb_file, ub_file, lbA_file, ubA_file, nWSR, cputime, xOpt, yOpt, Bounds.getCPtr(guessedBounds), guessedBounds, Constraints.getCPtr(guessedConstraints), guessedConstraints));
  }

  public returnValue hotstart(double[] g_new, double[] lb_new, double[] ub_new, double[] lbA_new, double[] ubA_new, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_hotstart__SWIG_0(swigCPtr, this, g_new, lb_new, ub_new, lbA_new, ubA_new, nWSR, cputime));
  }

  public returnValue hotstart(double[] g_new, double[] lb_new, double[] ub_new, double[] lbA_new, double[] ubA_new, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_hotstart__SWIG_1(swigCPtr, this, g_new, lb_new, ub_new, lbA_new, ubA_new, nWSR));
  }

  public returnValue hotstart(String g_file, String lb_file, String ub_file, String lbA_file, String ubA_file, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_hotstart__SWIG_2(swigCPtr, this, g_file, lb_file, ub_file, lbA_file, ubA_file, nWSR, cputime));
  }

  public returnValue hotstart(String g_file, String lb_file, String ub_file, String lbA_file, String ubA_file, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_hotstart__SWIG_3(swigCPtr, this, g_file, lb_file, ub_file, lbA_file, ubA_file, nWSR));
  }

  public returnValue hotstart(double[] g_new, double[] lb_new, double[] ub_new, double[] lbA_new, double[] ubA_new, int[] nWSR, double[] cputime, Bounds guessedBounds, Constraints guessedConstraints) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_hotstart__SWIG_4(swigCPtr, this, g_new, lb_new, ub_new, lbA_new, ubA_new, nWSR, cputime, Bounds.getCPtr(guessedBounds), guessedBounds, Constraints.getCPtr(guessedConstraints), guessedConstraints));
  }

  public returnValue hotstart(String g_file, String lb_file, String ub_file, String lbA_file, String ubA_file, int[] nWSR, double[] cputime, Bounds guessedBounds, Constraints guessedConstraints) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_hotstart__SWIG_5(swigCPtr, this, g_file, lb_file, ub_file, lbA_file, ubA_file, nWSR, cputime, Bounds.getCPtr(guessedBounds), guessedBounds, Constraints.getCPtr(guessedConstraints), guessedConstraints));
  }

  public returnValue solveCurrentEQP(int n_rhs, double[] g_in, double[] lb_in, double[] ub_in, double[] lbA_in, double[] ubA_in, double[] x_out, double[] y_out) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_solveCurrentEQP(swigCPtr, this, n_rhs, g_in, lb_in, ub_in, lbA_in, ubA_in, x_out, y_out));
  }

  public returnValue getWorkingSet(double[] workingSet) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_getWorkingSet(swigCPtr, this, workingSet));
  }

  public returnValue getConstraints(Constraints _constraints) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_getConstraints(swigCPtr, this, Constraints.getCPtr(_constraints), _constraints));
  }

  public int getNC() {
    return qpOASESJNI.QProblem_getNC(swigCPtr, this);
  }

  public int getNEC() {
    return qpOASESJNI.QProblem_getNEC(swigCPtr, this);
  }

  public int getNAC() {
    return qpOASESJNI.QProblem_getNAC(swigCPtr, this);
  }

  public int getNIAC() {
    return qpOASESJNI.QProblem_getNIAC(swigCPtr, this);
  }

  public int getNZ() {
    return qpOASESJNI.QProblem_getNZ(swigCPtr, this);
  }

  public returnValue getDualSolution(double[] yOpt) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_getDualSolution(swigCPtr, this, yOpt));
  }

  public returnValue setConstraintProduct(ConstraintProduct _constraintProduct) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_setConstraintProduct(swigCPtr, this, ConstraintProduct.getCPtr(_constraintProduct), _constraintProduct));
  }

  public returnValue printProperties() {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_printProperties(swigCPtr, this));
  }

  public returnValue writeQpDataIntoMatFile(String filename) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_writeQpDataIntoMatFile(swigCPtr, this, filename));
  }

  public returnValue writeQpWorkspaceIntoMatFile(String filename) {
    return returnValue.swigToEnum(qpOASESJNI.QProblem_writeQpWorkspaceIntoMatFile(swigCPtr, this, filename));
  }

}
