/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public enum QProblemStatus {
  QPS_NOTINITIALISED,
  QPS_PREPARINGAUXILIARYQP,
  QPS_AUXILIARYQPSOLVED,
  QPS_PERFORMINGHOMOTOPY,
  QPS_HOMOTOPYQPSOLVED,
  QPS_SOLVED;

  public final int swigValue() {
    return swigValue;
  }

  public static QProblemStatus swigToEnum(int swigValue) {
    QProblemStatus[] swigValues = QProblemStatus.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (QProblemStatus swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + QProblemStatus.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private QProblemStatus() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private QProblemStatus(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private QProblemStatus(QProblemStatus swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

