/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class QProblemB {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected QProblemB(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QProblemB obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qpOASESJNI.delete_QProblemB(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public QProblemB() {
    this(qpOASESJNI.new_QProblemB__SWIG_0(), true);
  }

  public QProblemB(int _nV, HessianType _hessianType) {
    this(qpOASESJNI.new_QProblemB__SWIG_1(_nV, _hessianType.swigValue()), true);
  }

  public QProblemB(int _nV) {
    this(qpOASESJNI.new_QProblemB__SWIG_2(_nV), true);
  }

  public QProblemB(QProblemB rhs) {
    this(qpOASESJNI.new_QProblemB__SWIG_3(QProblemB.getCPtr(rhs), rhs), true);
  }

  public returnValue reset() {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_reset(swigCPtr, this));
  }

  public returnValue init(SymmetricMatrix _H, double[] _g, double[] _lb, double[] _ub, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_init__SWIG_0(swigCPtr, this, SymmetricMatrix.getCPtr(_H), _H, _g, _lb, _ub, nWSR, cputime));
  }

  public returnValue init(SymmetricMatrix _H, double[] _g, double[] _lb, double[] _ub, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_init__SWIG_1(swigCPtr, this, SymmetricMatrix.getCPtr(_H), _H, _g, _lb, _ub, nWSR));
  }

  public returnValue init(double[] _H, double[] _g, double[] _lb, double[] _ub, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_init__SWIG_2(swigCPtr, this, _H, _g, _lb, _ub, nWSR, cputime));
  }

  public returnValue init(double[] _H, double[] _g, double[] _lb, double[] _ub, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_init__SWIG_3(swigCPtr, this, _H, _g, _lb, _ub, nWSR));
  }

  public returnValue init(String H_file, String g_file, String lb_file, String ub_file, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_init__SWIG_4(swigCPtr, this, H_file, g_file, lb_file, ub_file, nWSR, cputime));
  }

  public returnValue init(String H_file, String g_file, String lb_file, String ub_file, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_init__SWIG_5(swigCPtr, this, H_file, g_file, lb_file, ub_file, nWSR));
  }

  public returnValue init(SymmetricMatrix _H, double[] _g, double[] _lb, double[] _ub, int[] nWSR, double[] cputime, double[] xOpt, double[] yOpt, Bounds guessedBounds) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_init__SWIG_6(swigCPtr, this, SymmetricMatrix.getCPtr(_H), _H, _g, _lb, _ub, nWSR, cputime, xOpt, yOpt, Bounds.getCPtr(guessedBounds), guessedBounds));
  }

  public returnValue init(double[] _H, double[] _g, double[] _lb, double[] _ub, int[] nWSR, double[] cputime, double[] xOpt, double[] yOpt, Bounds guessedBounds) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_init__SWIG_7(swigCPtr, this, _H, _g, _lb, _ub, nWSR, cputime, xOpt, yOpt, Bounds.getCPtr(guessedBounds), guessedBounds));
  }

  public returnValue init(String H_file, String g_file, String lb_file, String ub_file, int[] nWSR, double[] cputime, double[] xOpt, double[] yOpt, Bounds guessedBounds) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_init__SWIG_8(swigCPtr, this, H_file, g_file, lb_file, ub_file, nWSR, cputime, xOpt, yOpt, Bounds.getCPtr(guessedBounds), guessedBounds));
  }

  public returnValue hotstart(double[] g_new, double[] lb_new, double[] ub_new, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_hotstart__SWIG_0(swigCPtr, this, g_new, lb_new, ub_new, nWSR, cputime));
  }

  public returnValue hotstart(double[] g_new, double[] lb_new, double[] ub_new, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_hotstart__SWIG_1(swigCPtr, this, g_new, lb_new, ub_new, nWSR));
  }

  public returnValue hotstart(String g_file, String lb_file, String ub_file, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_hotstart__SWIG_2(swigCPtr, this, g_file, lb_file, ub_file, nWSR, cputime));
  }

  public returnValue hotstart(String g_file, String lb_file, String ub_file, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_hotstart__SWIG_3(swigCPtr, this, g_file, lb_file, ub_file, nWSR));
  }

  public returnValue hotstart(double[] g_new, double[] lb_new, double[] ub_new, int[] nWSR, double[] cputime, Bounds guessedBounds) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_hotstart__SWIG_4(swigCPtr, this, g_new, lb_new, ub_new, nWSR, cputime, Bounds.getCPtr(guessedBounds), guessedBounds));
  }

  public returnValue hotstart(String g_file, String lb_file, String ub_file, int[] nWSR, double[] cputime, Bounds guessedBounds) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_hotstart__SWIG_5(swigCPtr, this, g_file, lb_file, ub_file, nWSR, cputime, Bounds.getCPtr(guessedBounds), guessedBounds));
  }

  public returnValue getWorkingSet(double[] workingSet) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_getWorkingSet(swigCPtr, this, workingSet));
  }

  public returnValue getBounds(Bounds _bounds) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_getBounds(swigCPtr, this, Bounds.getCPtr(_bounds), _bounds));
  }

  public int getNV() {
    return qpOASESJNI.QProblemB_getNV(swigCPtr, this);
  }

  public int getNFR() {
    return qpOASESJNI.QProblemB_getNFR(swigCPtr, this);
  }

  public int getNFX() {
    return qpOASESJNI.QProblemB_getNFX(swigCPtr, this);
  }

  public int getNFV() {
    return qpOASESJNI.QProblemB_getNFV(swigCPtr, this);
  }

  public int getNZ() {
    return qpOASESJNI.QProblemB_getNZ(swigCPtr, this);
  }

  public double getObjVal() {
    return qpOASESJNI.QProblemB_getObjVal__SWIG_0(swigCPtr, this);
  }

  public double getObjVal(double[] _x) {
    return qpOASESJNI.QProblemB_getObjVal__SWIG_1(swigCPtr, this, _x);
  }

  public returnValue getPrimalSolution(double[] xOpt) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_getPrimalSolution(swigCPtr, this, xOpt));
  }

  public returnValue getDualSolution(double[] yOpt) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_getDualSolution(swigCPtr, this, yOpt));
  }

  public QProblemStatus getStatus() {
    return QProblemStatus.swigToEnum(qpOASESJNI.QProblemB_getStatus(swigCPtr, this));
  }

  public BooleanType isInitialised() {
    return BooleanType.swigToEnum(qpOASESJNI.QProblemB_isInitialised(swigCPtr, this));
  }

  public BooleanType isSolved() {
    return BooleanType.swigToEnum(qpOASESJNI.QProblemB_isSolved(swigCPtr, this));
  }

  public BooleanType isInfeasible() {
    return BooleanType.swigToEnum(qpOASESJNI.QProblemB_isInfeasible(swigCPtr, this));
  }

  public BooleanType isUnbounded() {
    return BooleanType.swigToEnum(qpOASESJNI.QProblemB_isUnbounded(swigCPtr, this));
  }

  public HessianType getHessianType() {
    return HessianType.swigToEnum(qpOASESJNI.QProblemB_getHessianType(swigCPtr, this));
  }

  public returnValue setHessianType(HessianType _hessianType) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_setHessianType(swigCPtr, this, _hessianType.swigValue()));
  }

  public BooleanType usingRegularisation() {
    return BooleanType.swigToEnum(qpOASESJNI.QProblemB_usingRegularisation(swigCPtr, this));
  }

  public Options getOptions() {
    return new Options(qpOASESJNI.QProblemB_getOptions(swigCPtr, this), true);
  }

  public returnValue setOptions(Options _options) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_setOptions(swigCPtr, this, Options.getCPtr(_options), _options));
  }

  public PrintLevel getPrintLevel() {
    return PrintLevel.swigToEnum(qpOASESJNI.QProblemB_getPrintLevel(swigCPtr, this));
  }

  public returnValue setPrintLevel(PrintLevel _printlevel) {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_setPrintLevel(swigCPtr, this, _printlevel.swigValue()));
  }

  public returnValue printProperties() {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_printProperties(swigCPtr, this));
  }

  public returnValue printOptions() {
    return returnValue.swigToEnum(qpOASESJNI.QProblemB_printOptions(swigCPtr, this));
  }

}
