/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class SQProblem extends QProblem {
  private long swigCPtr;

  protected SQProblem(long cPtr, boolean cMemoryOwn) {
    super(qpOASESJNI.SQProblem_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SQProblem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qpOASESJNI.delete_SQProblem(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SQProblem() {
    this(qpOASESJNI.new_SQProblem__SWIG_0(), true);
  }

  public SQProblem(int _nV, int _nC, HessianType _hessianType) {
    this(qpOASESJNI.new_SQProblem__SWIG_1(_nV, _nC, _hessianType.swigValue()), true);
  }

  public SQProblem(int _nV, int _nC) {
    this(qpOASESJNI.new_SQProblem__SWIG_2(_nV, _nC), true);
  }

  public SQProblem(SQProblem rhs) {
    this(qpOASESJNI.new_SQProblem__SWIG_3(SQProblem.getCPtr(rhs), rhs), true);
  }

  public returnValue hotstart(double[] H_new, double[] g_new, double[] A_new, double[] lb_new, double[] ub_new, double[] lbA_new, double[] ubA_new, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.SQProblem_hotstart__SWIG_0(swigCPtr, this, H_new, g_new, A_new, lb_new, ub_new, lbA_new, ubA_new, nWSR, cputime));
  }

  public returnValue hotstart(double[] H_new, double[] g_new, double[] A_new, double[] lb_new, double[] ub_new, double[] lbA_new, double[] ubA_new, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.SQProblem_hotstart__SWIG_1(swigCPtr, this, H_new, g_new, A_new, lb_new, ub_new, lbA_new, ubA_new, nWSR));
  }

  public returnValue hotstart(String H_file, String g_file, String A_file, String lb_file, String ub_file, String lbA_file, String ubA_file, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.SQProblem_hotstart__SWIG_2(swigCPtr, this, H_file, g_file, A_file, lb_file, ub_file, lbA_file, ubA_file, nWSR, cputime));
  }

  public returnValue hotstart(String H_file, String g_file, String A_file, String lb_file, String ub_file, String lbA_file, String ubA_file, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.SQProblem_hotstart__SWIG_3(swigCPtr, this, H_file, g_file, A_file, lb_file, ub_file, lbA_file, ubA_file, nWSR));
  }

  public returnValue hotstart(SymmetricMatrix H_new, double[] g_new, Matrix A_new, double[] lb_new, double[] ub_new, double[] lbA_new, double[] ubA_new, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.SQProblem_hotstart__SWIG_4(swigCPtr, this, SymmetricMatrix.getCPtr(H_new), H_new, g_new, Matrix.getCPtr(A_new), A_new, lb_new, ub_new, lbA_new, ubA_new, nWSR, cputime));
  }

  public returnValue hotstart(SymmetricMatrix H_new, double[] g_new, Matrix A_new, double[] lb_new, double[] ub_new, double[] lbA_new, double[] ubA_new, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.SQProblem_hotstart__SWIG_5(swigCPtr, this, SymmetricMatrix.getCPtr(H_new), H_new, g_new, Matrix.getCPtr(A_new), A_new, lb_new, ub_new, lbA_new, ubA_new, nWSR));
  }

  public returnValue hotstart(double[] g_new, double[] lb_new, double[] ub_new, double[] lbA_new, double[] ubA_new, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.SQProblem_hotstart__SWIG_6(swigCPtr, this, g_new, lb_new, ub_new, lbA_new, ubA_new, nWSR, cputime));
  }

  public returnValue hotstart(double[] g_new, double[] lb_new, double[] ub_new, double[] lbA_new, double[] ubA_new, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.SQProblem_hotstart__SWIG_7(swigCPtr, this, g_new, lb_new, ub_new, lbA_new, ubA_new, nWSR));
  }

  public returnValue hotstart(String g_file, String lb_file, String ub_file, String lbA_file, String ubA_file, int[] nWSR, double[] cputime) {
    return returnValue.swigToEnum(qpOASESJNI.SQProblem_hotstart__SWIG_8(swigCPtr, this, g_file, lb_file, ub_file, lbA_file, ubA_file, nWSR, cputime));
  }

  public returnValue hotstart(String g_file, String lb_file, String ub_file, String lbA_file, String ubA_file, int[] nWSR) {
    return returnValue.swigToEnum(qpOASESJNI.SQProblem_hotstart__SWIG_9(swigCPtr, this, g_file, lb_file, ub_file, lbA_file, ubA_file, nWSR));
  }

  public returnValue hotstart(double[] g_new, double[] lb_new, double[] ub_new, double[] lbA_new, double[] ubA_new, int[] nWSR, double[] cputime, Bounds guessedBounds, Constraints guessedConstraints) {
    return returnValue.swigToEnum(qpOASESJNI.SQProblem_hotstart__SWIG_10(swigCPtr, this, g_new, lb_new, ub_new, lbA_new, ubA_new, nWSR, cputime, Bounds.getCPtr(guessedBounds), guessedBounds, Constraints.getCPtr(guessedConstraints), guessedConstraints));
  }

  public returnValue hotstart(String g_file, String lb_file, String ub_file, String lbA_file, String ubA_file, int[] nWSR, double[] cputime, Bounds guessedBounds, Constraints guessedConstraints) {
    return returnValue.swigToEnum(qpOASESJNI.SQProblem_hotstart__SWIG_11(swigCPtr, this, g_file, lb_file, ub_file, lbA_file, ubA_file, nWSR, cputime, Bounds.getCPtr(guessedBounds), guessedBounds, Constraints.getCPtr(guessedConstraints), guessedConstraints));
  }

}
