/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public enum SubjectToType {
  ST_UNBOUNDED,
  ST_BOUNDED,
  ST_EQUALITY,
  ST_DISABLED,
  ST_UNKNOWN;

  public final int swigValue() {
    return swigValue;
  }

  public static SubjectToType swigToEnum(int swigValue) {
    SubjectToType[] swigValues = SubjectToType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (SubjectToType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + SubjectToType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private SubjectToType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private SubjectToType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private SubjectToType(SubjectToType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

