/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class SubjectTo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SubjectTo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubjectTo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qpOASESJNI.delete_SubjectTo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public returnValue init(int _n) {
    return returnValue.swigToEnum(qpOASESJNI.SubjectTo_init__SWIG_0(swigCPtr, this, _n));
  }

  public returnValue init() {
    return returnValue.swigToEnum(qpOASESJNI.SubjectTo_init__SWIG_1(swigCPtr, this));
  }

  public int getNumberOfType(SubjectToType _type) {
    return qpOASESJNI.SubjectTo_getNumberOfType(swigCPtr, this, _type.swigValue());
  }

  public SubjectToType getType(int i) {
    return SubjectToType.swigToEnum(qpOASESJNI.SubjectTo_getType(swigCPtr, this, i));
  }

  public SubjectToStatus getStatus(int i) {
    return SubjectToStatus.swigToEnum(qpOASESJNI.SubjectTo_getStatus(swigCPtr, this, i));
  }

  public returnValue setType(int i, SubjectToType value) {
    return returnValue.swigToEnum(qpOASESJNI.SubjectTo_setType(swigCPtr, this, i, value.swigValue()));
  }

  public returnValue setStatus(int i, SubjectToStatus value) {
    return returnValue.swigToEnum(qpOASESJNI.SubjectTo_setStatus(swigCPtr, this, i, value.swigValue()));
  }

  public void setNoLower(BooleanType _status) {
    qpOASESJNI.SubjectTo_setNoLower(swigCPtr, this, _status.swigValue());
  }

  public void setNoUpper(BooleanType _status) {
    qpOASESJNI.SubjectTo_setNoUpper(swigCPtr, this, _status.swigValue());
  }

  public BooleanType hasNoLower() {
    return BooleanType.swigToEnum(qpOASESJNI.SubjectTo_hasNoLower(swigCPtr, this));
  }

  public BooleanType hasNoUpper() {
    return BooleanType.swigToEnum(qpOASESJNI.SubjectTo_hasNoUpper(swigCPtr, this));
  }

  public returnValue shift(int offset) {
    return returnValue.swigToEnum(qpOASESJNI.SubjectTo_shift(swigCPtr, this, offset));
  }

  public returnValue rotate(int offset) {
    return returnValue.swigToEnum(qpOASESJNI.SubjectTo_rotate(swigCPtr, this, offset));
  }

}
