/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class SymDenseMat extends DenseMatrix {
  private long swigCPtr;

  protected SymDenseMat(long cPtr, boolean cMemoryOwn) {
    super(qpOASESJNI.SymDenseMat_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SymDenseMat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qpOASESJNI.delete_SymDenseMat(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SymDenseMat() {
    this(qpOASESJNI.new_SymDenseMat__SWIG_0(), true);
  }

  public SymDenseMat(int m, int n, int lD, double[] v) {
    this(qpOASESJNI.new_SymDenseMat__SWIG_1(m, n, lD, v), true);
  }

  public Matrix duplicate() {
    long cPtr = qpOASESJNI.SymDenseMat_duplicate(swigCPtr, this);
    return (cPtr == 0) ? null : new Matrix(cPtr, false);
  }

  public SymmetricMatrix duplicateSym() {
    long cPtr = qpOASESJNI.SymDenseMat_duplicateSym(swigCPtr, this);
    return (cPtr == 0) ? null : new SymmetricMatrix(cPtr, false);
  }

  public returnValue bilinear(Indexlist icols, int xN, double[] x, int xLD, double[] y, int yLD) {
    return returnValue.swigToEnum(qpOASESJNI.SymDenseMat_bilinear(swigCPtr, this, Indexlist.getCPtr(icols), icols, xN, x, xLD, y, yLD));
  }

}
