/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.convexOptimization.qpOASES;

public class TabularOutput {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TabularOutput(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TabularOutput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qpOASESJNI.delete_TabularOutput(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIdxAddB(int value) {
    qpOASESJNI.TabularOutput_idxAddB_set(swigCPtr, this, value);
  }

  public int getIdxAddB() {
    return qpOASESJNI.TabularOutput_idxAddB_get(swigCPtr, this);
  }

  public void setIdxRemB(int value) {
    qpOASESJNI.TabularOutput_idxRemB_set(swigCPtr, this, value);
  }

  public int getIdxRemB() {
    return qpOASESJNI.TabularOutput_idxRemB_get(swigCPtr, this);
  }

  public void setIdxAddC(int value) {
    qpOASESJNI.TabularOutput_idxAddC_set(swigCPtr, this, value);
  }

  public int getIdxAddC() {
    return qpOASESJNI.TabularOutput_idxAddC_get(swigCPtr, this);
  }

  public void setIdxRemC(int value) {
    qpOASESJNI.TabularOutput_idxRemC_set(swigCPtr, this, value);
  }

  public int getIdxRemC() {
    return qpOASESJNI.TabularOutput_idxRemC_get(swigCPtr, this);
  }

  public void setExcAddB(int value) {
    qpOASESJNI.TabularOutput_excAddB_set(swigCPtr, this, value);
  }

  public int getExcAddB() {
    return qpOASESJNI.TabularOutput_excAddB_get(swigCPtr, this);
  }

  public void setExcRemB(int value) {
    qpOASESJNI.TabularOutput_excRemB_set(swigCPtr, this, value);
  }

  public int getExcRemB() {
    return qpOASESJNI.TabularOutput_excRemB_get(swigCPtr, this);
  }

  public void setExcAddC(int value) {
    qpOASESJNI.TabularOutput_excAddC_set(swigCPtr, this, value);
  }

  public int getExcAddC() {
    return qpOASESJNI.TabularOutput_excAddC_get(swigCPtr, this);
  }

  public void setExcRemC(int value) {
    qpOASESJNI.TabularOutput_excRemC_set(swigCPtr, this, value);
  }

  public int getExcRemC() {
    return qpOASESJNI.TabularOutput_excRemC_get(swigCPtr, this);
  }

  public TabularOutput() {
    this(qpOASESJNI.new_TabularOutput(), true);
  }

}
