/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_ihmc_convexOptimization_QpOASESJNISolver */

#ifndef _Included_us_ihmc_convexOptimization_QpOASESJNISolver
#define _Included_us_ihmc_convexOptimization_QpOASESJNISolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    solveJNI
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_solveJNI
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    hotstartJNI
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_hotstartJNI
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    initializeJNI
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_initializeJNI
        (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    createSolver
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_createSolver
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_A_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_A_Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_x_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_x_Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_H_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_H_Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_g_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_g_Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_lb_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_lb_Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_ub_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_ub_Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_lbA_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_lbA_Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_ubA_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_ubA_Buffer
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
