/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_ihmc_convexOptimization_QpOASESJNISolver */

#ifndef _Included_us_ihmc_convexOptimization_QpOASESJNISolver
#define _Included_us_ihmc_convexOptimization_QpOASESJNISolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    solveJNI
 * Signature: (IDJ)I
 */
JNIEXPORT jint JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_solveJNI
        (JNIEnv *, jobject, jint, jdouble, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    hotstartJNI
 * Signature: (IDJ)I
 */
JNIEXPORT jint JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_hotstartJNI
        (JNIEnv *, jobject, jint, jdouble, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    initializeJNI
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_initializeJNI
        (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    createSolver
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_createSolver
        (JNIEnv *, jobject);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    setHessianTypeOrdinal
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_setHessianTypeOrdinal
        (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    setSolverOptionOrdinal
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_setSolverOptionOrdinal
        (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_A_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_1A_1Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_x_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_1x_1Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_H_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_1H_1Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_g_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_1g_1Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_lb_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_1lb_1Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_ub_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_1ub_1Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_lbA_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_1lbA_1Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    get_ubA_Buffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_get_1ubA_1Buffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    getNumberOfWorkingSetChangesFromNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_getNumberOfWorkingSetChangesFromNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    getCPUTimeFromNative
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_getCPUTimeFromNative
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    getObjValueFromNative
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_getObjValueFromNative
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
