/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_ihmc_convexOptimization_QpOASESJNISolver */

#ifndef _Included_us_ihmc_convexOptimization_QpOASESJNISolver
#define _Included_us_ihmc_convexOptimization_QpOASESJNISolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    solveJNI
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_solveJNI
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    hotstartJNI
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_hotstartJNI
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    initializeJNI
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_initializeJNI
        (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    createSolver
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_createSolver
        (JNIEnv *, jobject);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    getABuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_getABuffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    getXBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_getXBuffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    getHessianBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_getHessianBuffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    getGradientBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_getGradientBuffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    getLowerBoundBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_getLowerBoundBuffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    getUpperBoundBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_getUpperBoundBuffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    getLowerBoundABuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_getLowerBoundABuffer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_convexOptimization_QpOASESJNISolver
 * Method:    getUpperBoundABuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_convexOptimization_QpOASESJNISolver_getUpperBoundABuffer
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
